INSERT INTO zhanqu.zq_organizer (name, company_created_at, enabled, logo, manager_id, username, password) VALUES ('高政平测试', '2015-10-16 17:26:07', 1, 'uploads/20151224/74781450955392.png', 39, 'zhubanfang', '123456');
INSERT INTO zhanqu.zq_organizer (name, company_created_at, enabled, logo, manager_id, username, password) VALUES ('老张', null, 1, null, 41, 'zyq', '123456');
INSERT INTO zhanqu.zq_organizer (name, company_created_at, enabled, logo, manager_id, username, password) VALUES ('公司名字123', null, 1, null, 48, 'aqing', 'aqing');
INSERT INTO zhanqu.zq_organizer (name, company_created_at, enabled, logo, manager_id, username, password) VALUES ('咸宁会展', null, 1, null, 52, 'xnzh', '123456');
INSERT INTO zhanqu.zq_organizer (name, company_created_at, enabled, logo, manager_id, username, password) VALUES ('高政平测试', null, 1, null, 62, 'gzptest', '123456');
INSERT INTO zhanqu.zq_organizer (name, company_created_at, enabled, logo, manager_id, username, password) VALUES ('陈林有限公司', null, 1, null, 63, 'chenlin', '123456');
INSERT INTO zhanqu.zq_organizer (name, company_created_at, enabled, logo, manager_id, username, password) VALUES ('test', null, 1, null, 108, '123456', '123456');
INSERT INTO zhanqu.zq_organizer (name, company_created_at, enabled, logo, manager_id, username, password) VALUES ('高家大院', null, 1, null, 144, 'gaojiada', '123456');
INSERT INTO zhanqu.zq_organizer (name, company_created_at, enabled, logo, manager_id, username, password) VALUES ('尚格市场运营管理中心', null, 1, null, 155, 'ccrsg', '123456');
INSERT INTO zhanqu.zq_organizer (name, company_created_at, enabled, logo, manager_id, username, password) VALUES ('aqing1', null, 1, null, 156, 'aqing1', 'aqing1');
INSERT INTO zhanqu.zq_organizer (name, company_created_at, enabled, logo, manager_id, username, password) VALUES ('尚格市场部一', null, 1, null, 157, 'sgmk1', '123456');
INSERT INTO zhanqu.zq_organizer (name, company_created_at, enabled, logo, manager_id, username, password) VALUES ('尚格市场部二', null, 1, null, 158, 'sgmk2', '123456');
INSERT INTO zhanqu.zq_organizer (name, company_created_at, enabled, logo, manager_id, username, password) VALUES ('老同志', null, 1, null, 23291, 'laotz', '12345678');
INSERT INTO zhanqu.zq_organizer (name, company_created_at, enabled, logo, manager_id, username, password) VALUES ('lala1', null, 1, null, 27278, 'dulala', 'dulala');
INSERT INTO zhanqu.zq_organizer (name, company_created_at, enabled, logo, manager_id, username, password) VALUES ('尚格', null, 1, null, 27280, 'lsc', '123456');
INSERT INTO zhanqu.zq_organizer (name, company_created_at, enabled, logo, manager_id, username, password) VALUES ('公司名称', null, null, null, 27325, '用户名', '123456');